package com.softeam.rules.visa

import rfagot.examples.drools_620_conwaysgameoflife.model.Cell;

rule "Makes cell dead if she has less than 1 or more than 3 neightbours"
dialect "mvel"

	when
		currentCell : Cell(state == Cell.ALIVE)
		nbNeighbours : Number( this < 2 || this > 3) 
				from accumulate (
		$cell : Cell((state == Cell.ALIVE) &&
					(
		              ((posX == (currentCell.posX - 1)) && (posY == (currentCell.posY + 1)))
		           || ((posX == currentCell.posX)       && (posY == (currentCell.posY + 1)))
		           || ((posX == (currentCell.posX + 1)) && (posY == (currentCell.posY + 1)))
		           
		           || ((posX == (currentCell.posX - 1)) && (posY == currentCell.posY))
		           || ((posX == (currentCell.posX + 1)) && (posY == currentCell.posY))
		           
		           || ((posX == (currentCell.posX - 1)) && (posY == (currentCell.posY - 1)))
		           || ((posX == currentCell.posX )      && (posY == (currentCell.posY - 1)))
		           || ((posX == (currentCell.posX + 1)) && (posY == (currentCell.posY - 1)))
		           
		           ))
		
		, count($cell))
		
	then
		currentCell.state = Cell.DEAD;		
end 